# Data Structure {#intro}

The Itrax core scanner is a multi-sensor device, with separate data outputs for different measurements and uses. They are described in the following sections. Note that your data may not contain all of these objects, depending on the exact scanner, configuration, or data repository you use. The folder structure may vary between operators, but typically there will be a folder for each scan section, and each will contain the data described in the following sections. 

Note that where radiographs and XRF data have been acquired using different step-sizes (measurement intervals), the operator will create separate scan sections (folders) for the x-radiograph and XRF measurement. This is because a scan section can only have a single fixed step-size. For example, it is not uncommon for users to require an step-size of 200 μm for the x-radiograph, but only 1 mm for the XRF measurement. 

## Metadata

Every scan folder has a `document.txt` file that contains information about the parameters of the scan. For example, it contains the current and voltage settings used for the x-ray tube, the step size, and the start and stop positions of the scan. It is a text file, although the formatting can be inconsistently rendered depending on the text editor used. Sometimes this information is required to process other parts of the data, and as such it is an important part of the overall data package. 

## XRF Data

The XRF data can be split into two groups --- "raw" and "processed" data. The raw data is contained in a separate folder called `XRF data`, and consists of a single file, beginning with `L000000.spe` and incrementing sequentially. This file can be read using a text editor and is tab-delimited. The first part is a header, containing metadata information. The second part is a table of all the channels of the detector and the corresponding count for each channel. Increasing channel numbers represent increasing energy, but some thought needs to be given to calibrating channels into an energy --- this step is usually performed using specialist software. In addition, a file called `sumspectra.spe` is often included in the root directory; this is simply the sum of all the `*.spe` files in the `XRF data` directory, and is sometimes useful in processing the data. 

Processed data comes from the `Q-Spec` software (Cox Analytical Systems, Sweden) provided with the machine. Its function is to process the spectral data files (`*.spe`) into peak-areas for each element of interest by fitting a model to the data. The model needs some user input and intervention to optimise it, and the quality of the model can be assessed using a number of diagnostic parameters, the most important being the root-mean-squared-error (RMSE). The `Q-Spec` software can also perform some quantitative calibration of the data, although this is a less typical use-case. Often the operator will include a file that contains all of the settings used by `Q-Spec` to translate the raw data files into the peak area output file --- this file will have the extension `*.dfl` and will often simply be called `settings.dfl`. 

The processed elemental data comes in the form of a text file comprising of a tab-delimited table, with a single row for each measurement step, and a column for parameters including individual element peak areas in counts (n) or intensities (n/mA). The data files commonly have names like `result.txt` or `Results.txt`, but may have been subsequently renamed. These are the ED-XRF data most commonly worked with by analysts. 

## Optical Images

The scanner collects good quality optical images that have consistent lighting and because they are line-scan images, they do not suffer from optical distortions. Medium resolution images are usually included in all scan section folders (typically `optical.tif`), and optional high-resolution images are often included by operators elsewhere. High resolution images are typically supplied as both 8-bit and 16-bit images, and are usually hundreds of megabytes in size.

Although the brightness of the lighting in the scanner is adjustable, images sometimes need to be brightened and/or have the contrast adjusted. This can be performed in desktop publishing software (e.g. `Adobe Photoshop`, `Corel Photo-Draw`), but it is easiest to use the open-source scientific image analysis software `imageJ` (NIH, USA). 

By including an appropriate colour reference card in the scan the image can be calibrated, although it is often desirable to increase the contrast and gamma to elucidate features of the core. The photograph is always of the entire length of the bed scanned, rather than cropped to the limits of an individual scan section. If multiple scan sections are placed on the bed and are scanned together, it will include all of the scanned sections. The image needs to be cropped using the metadata for the relevant scan section; this process is covered in later chapters.

In this case, the colour reference information for the card in the image is given in the file `greywhitebalancecolourcard.csv`. The plugin for `imageJ`, [`ijp-color`](https://github.com/ij-plugins/ijp-color), can be used to perform colour calibration on the images. In this case a `linear - no incercept` model has been used. to generate the image files `image0.tif`.  

## Radiographic Images

The scanner has an x-radiographic line array capable of producing good-quality x-radiographs of the cores. The scan data can be split into two parts --- "raw" and "processed" data. The raw data (usually `radiograph.raw`) is a tab-delimited text file containing a matrix of greyscale values. Each column represents a single step (measurement interval, often set to between 50 and 200 μm), and each row represents a single pixel on the line array. The pixel spacing is around 20 μm. Note that the raw radiographic data contains pixels at the extremes that are outside of the coverage of the x-ray beam --- these are obviously useless and need to be cropped. 

The processed image (`radiograph.tif`) has a lower resolution than the raw data. This is because the pixels must be square, and so the pixels are down-sampled to fit with the step-size of the scan. Thus, if the step-size was 200 μm, each pixel will be 200 x 200 μm, whereas the raw data will have rectangular pixels with dimensions of 20 x 200 μm. The data at the extremes of the radiograph are always cropped, so the radiograph has a coverage of around 13 mm of the width of the core. 

Like the optical image, the radiograph often requires contrast and brightness adjustments, and these are easiest to perform in `imageJ`. With the inclusion of a suitable density standard, some relative or, where "u-channels" are used, absolute density calibration can be performed using these data; see @Francus2015 for more. 

## Magnetic Susceptability 

Some scanners include a Bartington MS2E surface sensor, but the example dataset supplied here does not have magnetic susceptability data collected from an Itrax core scanner. 
