--- 
title: "Using Itrax Data in R"
author: "Thomas Bishop"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: biblio.bib
biblio-style: apalike
link-citations: yes
description: This book is a guide to importing, tidying, manipulating and analysing
  Itrax core scanner data in R.
---

# Preface {-}

## Why did I write this book?
During the COVID-19 pandemic in 2020 it became necessary to formalise (or at least, organise) the support offered to students using the Itrax core scanner at The University of Manchester Geography Laboratories so they could be offered online. This led to an unexpectedly popular series of seminars. When these came to an end, we decided it would be useful to summarise our seminars into a reference guide that could be updated over time. This is that guide.  

## Prerequisites
This guide assumes a basic knowledge of `R` and the `tidyverse`, including data types, assignments, and pipes. It also assumes a background knowledge of the core scanner and the nature of the data it produces; see @Croudace2019 and references therein. Some of the sections on data analysis assume some knowledge of compositional data analysis. 

## Example Data
All of these examples given in this book are from Piston core CD166/19, which was recovered from the Agadir Basin during the RRS Charles Darwin expedition CD166 in 2004 @Wynn2005. The core site is located at 31°31’ N, 17°11.77’ W at a water depth of 4502 m. The coring operation recovered 4.3 m of sediment composed of hemipelagite and turbidites. The hemipelagic sediments range from cream-brown carbonate-rich marl/ooze to red-brown clays. The turbidites include siliciclastic, volcaniclastic and calcareous sediments.

The split core sections were analysed using the Cox Analytical Systems Itrax core scanner at the British Ocean Sediment Core Research Facility, National Oceanography Centre (Southampton, UK). The split core surfaces were cleaned and loaded to the core scanner along with a radiographic reference sample @Francus2015 and a colour card. The cores were first scanned to measure the sample surface height and to obtain optical images. The core sections were then covered with Mylar film to reduce sample desiccation during XRF scanning and x-radiography.

XRF data were acquired using a molybdenum X-ray tube set at 30 kV and 30 mA with a dwell time of 30 seconds and a step size of 1 mm. X-radiographs were acquired with voltage and current set to 55 kV and 50 mA, respectively, and dwell time set to 500 ms. Step size for the x-radiography was set to 200 µm. Two replicate XRF scans were also performed for each of the three core sections that make up this core. The XRF settings for the replicates were kept consistent with those of the main XRF scan. The interval selected for the replicate scans ranged from 10 cm to 15 cm of the the total sample length. All raw XRF raw data were reprocessed using the QSpec spectral analysis software to optimise peak fitting. 

The data can be downloaded from the Github pages that form the source for this document, available at [github.com/tombishop1/itraxBook](https://github.com/tombishop1/itraxBook). 

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "CD166_19_(2020)/")

# check if itraxR is installed, if not, install
if (!require("itraxR", character.only = TRUE)) {
  install.packages("remotes")
  remotes::install_github("tombishop1/itraxR")
  library(itraxR)
}

# now check dependencies
## First specify the packages of interest
# these are the dependencies for:
# the document - kableExtra, DiagrammeR
# itrax_import - readr, janitor, dplyr
# itrax_join   - dplyr
# itrax_meta   - none 
packages = c("janitor", "dplyr", "readr", "kableExtra", "DiagrammeR")

## Now load or install & load all those CRAN packages
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE, repos = "http://cran.uk.r-project.org")
      library(x, character.only = TRUE)
    }
  }
)
rm(package.check, packages)

```
